#!/usr/bin/env bash
# this scripts gives information about /etc/passwd file
while read -r passwd; do
	echo "$passwd" | (IFS=':' read -r username pass uid gid uidinfo home shell; echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $uidinfo")
done < "/etc/passwd"
